### ISSUE TITLE
Consider adding options YAML config

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/menu_commander#11]
Perhaps it would be nice to allow `options` in the YAML config. This ticket is a list of possible configuration options to consider:

- [x] Move the `header` option into `options > header` (#14).
- [x] Configure pagination size (currently hard coded to 10) (#14).
- [x] Configure filter behavior (currently shown only when there are 10 or more items) (#14).
- [x] Configure if we want to show ellipsis or some other character when the menu has sub menus (#14).
- [x] Configure if we want arg menus with one item to be automatically selected (#15).
- [x] ~Configure if we want to see and confirm each command before execution~
    - [x] AND/OR as a command line flag? (#12)
